#02_ nottoyage des donne Spotify 

objectif : identifier les probleme du jeu de donne justifie les traitement puis enregestrer un fichier ettoye pour analyses

In [2]:
from pathlib import Path
import pandas as pd

chemin_csv = Path("../data/raw/spotify-albums_data_2023.csv")

df = pd.read_csv(chemin_csv)

print("Dimension initiale :", df.shape)
display(df.head())

Dimension initiale : (438973, 26)

,track_name,track_id,track_number,duration_ms,album_type,artists,total_tracks,album_name,release_date,label,...,artist_3,artist_4,artist_5,artist_6,artist_7,artist_8,artist_9,artist_10,artist_11,duration_sec
0,Amazing Grace,6mN8nzCXWUeT5LWEcG1Utx,5,555521,album,NaN,9,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,555.521
1,Silent Night,58sgjtx3FOnBBEOd3BQE6C,8,535041,album,NaN,9,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,535.041
2,Ancient Canyons,45tQJhm0WSk5VWMZK3FsLK,1,545855,album,NaN,9,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,545.855
3,Pacha Mama Medicina,3VFD7QqkJSg0OR6yBwKl7A,6,305241,album,NaN,9,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,305.241
4,Palace Of Light,7LwJV5BEIC9BQnzvaBSyCc,7,351060,album,NaN,9,Deep Peace Experience,2015-06-09 00:00:00 UTC,Mountain Music Inc,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,351.060

In [7]:
colonnes_vides = df.columns[df.isna().all()].tolist()
print("Colonnes entiere vide : " , colonnes_vides)

df = df.drop(columns=colonnes_vides)

print("Dimensions apres suppression : " , df.shape)

Colonnes entiere vide :  []
Dimensions apres suppression :  (438973, 20)

In [9]:
nb_invalides = (df["duration_ms"] <= 0).sum()

print("Durées invalides avant nettoyage :", nb_invalides)

Durées invalides avant nettoyage : 2

In [10]:
df = df[df["duration_ms"] > 0].copy()

print("dimension apres suppression : " , df.shape)

dimension apres suppression :  (438971, 20)

In [11]:

df["release_date"] = pd.to_datetime(
    df["release_date"],
    errors="coerce",
    utc=True,
    format="mixed"
)

print(
    "Dates manquantes après conversion :",
    df["release_date"].isna().sum()
)

Dates manquantes après conversion : 23

In [12]:

dates_anciennes = df[df["release_date"].dt.year < 1950]

print("Nombre de morceaux avec une date avant 1950 :", len(dates_anciennes))

display(
    dates_anciennes[
        ["track_name", "artist_0", "album_name", "release_date"]
    ].head(20)
)

Nombre de morceaux avec une date avant 1950 : 283

,track_name,artist_0,album_name,release_date
18815,"Fidelio, Op. 72 / Act 1: ""O Wär' Ich Schon Mit...",Ludwig van Beethoven,"Beethoven: Fidelio, Op. 72: O Wär' Ich Schon M...",1929-01-01 00:00:00+00:00
22617,Die Fledermaus (Short Version): Part 1,Johann Strauss II,Strauss: Die Fledermaus: Part 1,1929-01-01 00:00:00+00:00
22618,Die Fledermaus (Short Version): Part 4,Johann Strauss II,Strauss: Die Fledermaus: Part 4,1929-01-01 00:00:00+00:00
22619,Die Fledermaus (Short Version): Part 9,Johann Strauss II,Strauss: Die Fledermaus: Part 9,1929-01-01 00:00:00+00:00
22620,Die Fledermaus (Short Version): Part 2,Johann Strauss II,Strauss: Die Fledermaus: Part 2,1929-01-01 00:00:00+00:00
22621,Die Fledermaus (Short Version): Part 7,Johann Strauss II,Strauss: Die Fledermaus: Part 7,1929-01-01 00:00:00+00:00
24565,"Der Rosenkavalier, Op. 59, Trv 227: ""Hab Mir'S...",Richard Strauss,"Strauss: Der Rosenkavalier, Op. 59, Trv 227: H...",1929-01-01 00:00:00+00:00
24566,"Ariadne Auf Naxos, Trv 228: Zerbinetta'S Scene",Richard Strauss,Strauss: Zerbinetta'S Scene,1933-01-01 00:00:00+00:00
46833,Pennies From Heaven (With Teddy Wilson & His O...,Billie Holiday,Lady Day: The Complete Billie Holiday On Colum...,1936-01-01 00:00:00+00:00
46834,Why Was I Born? (With Teddy Wilson & His Orche...,Billie Holiday,Lady Day: The Complete Billie Holiday On Colum...,1936-01-01 00:00:00+00:00
46835,The Mood That I'M In (With Teddy Wilson & His ...,Billie Holiday,Lady Day: The Complete Billie Holiday On Colum...,1936-01-01 00:00:00+00:00
46836,You Showed Me The Way (With Teddy Wilson & His...,Billie Holiday,Lady Day: The Complete Billie Holiday On Colum...,1936-01-01 00:00:00+00:00
46837,Who Loves You? (With Teddy Wilson & His Orches...,Billie Holiday,Lady Day: The Complete Billie Holiday On Colum...,1936-01-01 00:00:00+00:00
46838,That'S Life I Guess (With Teddy Wilson & His O...,Billie Holiday,Lady Day: The Complete Billie Holiday On Colum...,1936-01-01 00:00:00+00:00
46839,Easy To Love (With Teddy Wilson & His Orchestra),Billie Holiday,Lady Day: The Complete Billie Holiday On Colum...,1936-01-01 00:00:00+00:00
46840,My Last Affair (With Teddy Wilson & His Orches...,Billie Holiday,Lady Day: The Complete Billie Holiday On Colum...,1936-01-01 00:00:00+00:00
46841,"One, Two, Button Your Shoe",Billie Holiday,Lady Day: The Complete Billie Holiday On Colum...,1936-01-01 00:00:00+00:00
46842,This Year'S Kisses (With Teddy Wilson & His Or...,Billie Holiday,Lady Day: The Complete Billie Holiday On Colum...,1936-01-01 00:00:00+00:00
46843,"One Never Knows, Does One?",Billie Holiday,Lady Day: The Complete Billie Holiday On Colum...,1936-01-01 00:00:00+00:00
46844,I'Ve Got My Love To Keep Me Warm,Billie Holiday,Lady Day: The Complete Billie Holiday On Colum...,1936-01-01 00:00:00+00:00

In [13]:
print("Lignes entièrement dupliquées :", df.duplicated().sum())

print(
    "Identifiants track_id répétés :",
    df["track_id"].duplicated().sum()
)

Lignes entièrement dupliquées : 0
Identifiants track_id répétés : 25

In [14]:

dossier_processed = Path("../data/processed")
dossier_processed.mkdir(parents=True, exist_ok=True)


chemin_sortie = dossier_processed / "spotify_albums_clean.csv"

df.to_csv(chemin_sortie, index=False)

print("Fichier enregistré :", chemin_sortie)

Fichier enregistré : ..\data\processed\spotify_albums_clean.csv

In [15]:
print("Dimensions finales :", df.shape)

print("Durées invalides restantes :", (df["duration_ms"] <= 0).sum())

print("Lignes entièrement dupliquées restantes :", df.duplicated().sum())

print("Dates manquantes :", df["release_date"].isna().sum())

Dimensions finales : (438971, 20)
Durées invalides restantes : 0
Lignes entièrement dupliquées restantes : 0
Dates manquantes : 23

In [18]:
df[df["release_date"].isna()]

,track_name,track_id,track_number,duration_ms,album_type,total_tracks,album_name,release_date,label,album_popularity,album_id,artist_id,artist_0,artist_1,artist_2,artist_3,artist_4,artist_5,artist_6,duration_sec
44090,Wondrous Backdrops For Powerful Balance,79mZ9pM3291S9zHT0gN9Cy,2,139505,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,139.505
44091,Jazz Organ Soundtrack For Deep Reality,5M6Ba0HbkjiVUm6s1iznUA,14,145728,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,145.728
44092,Background For September Chills,26UV70eo5S2O5d2gW069Vo,13,156966,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,156.966
44093,Elegant September Chills,4o3nDWqgwq7ofxW5qqQznA,5,126595,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,126.595
44094,Sparkling Deep Reality,1x7GXMbngkEhkMPapKN8Ak,6,130589,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,130.589
44095,Fashionable Ambiance For Deep Reality,4TZH5Ggwvb04PYiKNERWCT,10,127523,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,127.523
44096,Cultured Music For Sunset Paradise,0N1EzJQvDo92fj88GwNcJy,1,128545,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,128.545
44097,Fantastic Saxophone Jazz - Vibe For September ...,7zCR1nVXzGOEnj72tquJZP,18,127523,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,127.523
44098,Jazz Organ Soundtrack For Deep Reality,50YLV6piFFxPPf0zdbVnLx,4,130589,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,130.589
44099,Awesome Backdrops For September Chills,611WCzTpjrFwShNcBLOjSk,12,134954,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,134.954
44100,Extraordinary Ambience For Sunset Paradise,4IItdvqlM2bpLnE4TJXaB4,19,132725,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,132.725
44101,Background For Powerful Balance,0biBb9elmESoF6Pf7Lf5Xo,3,148421,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,148.421
44102,Unique Music For Sunset Paradise,6arbyJtLjkrfZqNAANk1RL,11,133839,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,133.839
44103,Unique Ambiance For Deep Reality,7zweDHDtt5WFkqkXW4bTnu,20,145728,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,145.728
44104,Sprightly Moods For Deep Reality,1PENgGOFV3H5gwawuih0Ne,7,147121,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,147.121
44105,Thrilling Saxophone Jazz - Vibe For Twilight A...,6vyzRZPlUpnR0mLlqK4iVk,8,156966,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,156.966
44106,Grand Ambience For Twilight Ambiance,62MNnNRHLQo3rwGTgbEJ0g,9,147121,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,147.121
44107,Peaceful Deep Reality,7a8NchlR024P0SHRSMczoW,16,138390,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,138.390
44108,Playful Powerful Balance,2nCQP2nyfaDhz3XceWEl7F,15,160031,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,160.031
44109,Opulent Moods For September Chills,5BSolHsHRBnjkZfEahq41a,17,130589,album,20,(Quintet Jazz) Music For Nirvana Relax,NaT,Vortex Club,0,2Eg4CbmQk1vN9GZ9b1LS5E,3gET6vVLNBbsc4a2tmvRJX,Soft Romantic Jazz,NaN,NaN,NaN,NaN,NaN,NaN,130.589
99008,Canada To South Korea,3Z6xEq6mR6IlSRRTquLLCw,1,168000,single,1,Canada To South Korea,NaT,Loyalty Above All Lawz Co.,0,7LPRKYDlDO7d8WN89ajWtP,1z4NT4QTTF9gBrHUPKeGc8,Lil Woodie Wood,Kim Jasin,Derek,Jordan,NaN,NaN,NaN,168.000
162103,Raven Runs,23uMewhzlzw3iQ5Zd60Hna,1,211318,single,2,Raven Runs,NaT,The Fiction Engine,1,7AICHHe1HRKdWNpVnrz4BI,45mP0SYp87NHTnBKGjiu0Q,Art Neuro,NaN,NaN,NaN,NaN,NaN,NaN,211.318
162104,Waiting For A Vaccine,0Du8ZlgwUhCJmMMbM94A7F,2,221062,single,2,Raven Runs,NaT,The Fiction Engine,1,7AICHHe1HRKdWNpVnrz4BI,45mP0SYp87NHTnBKGjiu0Q,Art Neuro,NaN,NaN,NaN,NaN,NaN,NaN,221.062

In [22]:

df_clean = df.copy()

df_clean = df_clean.dropna(subset=["release_date"])


print("Dimensions finales :", df_clean.shape)
print("Dates manquantes :", df_clean["release_date"].isna().sum())

Dimensions finales : (438948, 20)
Dates manquantes : 0

**Traitement des dates de sortie manquantes**

Lors de l'inspection des données, j'ai identifié 23 lignes dont la date de sortie (`release_date`) était manquante.

J'ai choisi de supprimer ces lignes, car la date de sortie est nécessaire pour réaliser mon analyse temporelle des albums, notamment pour étudier leur évolution au fil des années.

Cette suppression représente environ 0,005 % du jeu de données initial nettoyé (438 971 lignes). Elle a donc un impact très faible sur le volume de données disponible.

Je n'ai pas remplacé les dates manquantes par des valeurs estimées afin de ne pas introduire de dates potentiellement incorrectes dans mon analyse.